name: syr-geo
channels:
  - r
  - conda-forge
dependencies:
  # for R
  - r-base=4.2.3
  # tidyverse (do manually to avoid dependency errors and dplyr <1.1.2 bug)
  - r-dplyr=1.1.2
  - r-forcats=1.0.0
  - r-ggplot2=3.4.2
  - r-haven=2.5.0
  - r-jsonlite=1.8.4
  - r-purrr=1.0.1
  - r-readr=2.1.4
  - r-readxl=1.4.2
  - r-rvest=1.0.2
  - r-stringr=1.5.0
  - r-tibble=3.2.1
  - r-tidyr=1.3.0
  # other stuff
  - r-dotenv=1.0.3
  - r-httr2=0.2.3
  - r-jqr=1.2.3 # googleway dep not finding sys libs when installed as googleway dep
  - r-kableExtra=1.3.4
  - r-lwgeom=0.2_11
  - r-rcpp=1.0.10 # manual addition to resolve dep errors of lwgeom
  - r-rmarkdown=2.21
  - r-sf=1.0.13
  - r-sjlabelled=1.2.0
  - r-stringi=1.7.12 # manual addition to resolve dep errors of stringr
  - r-terra=1.7_29
  - r-tictoc=1.2
  - r-units=0.8_2
  # vscode interaction
  - r-languageserver=0.3.15
  - r-httpgd=1.3.1
  - radian=0.6.5
  # other useful stuff
  - cmake=3.26.3
  - pandoc
  - tectonic=0.12.0

# googleway=2.7.6
# pbapply=1.7-0
# smoothr=1.0.1
# tidyterra=0.4.0